---
title: "git_00"
author: "Harun Muhammade"
date: "09/04/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
A boat beneath a sunny sky,  
Lingering onward dreamily  
In an evening of July —   
Children three that nestle near,  
Eager eye and willing ear,  

 
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
I have been one acquainted with the night.  
I have walked out in rain—and back in rain.    
I have outwalked the furthest city light.     
I have looked down the saddest city lane.        
I have passed by the watchman on his beat      



## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night.  
The moon was shining sulkily  
,Because she thought the sun  
Had got no business to be there  
After the day was done —  
It's very rude of him," she said,  
"To come and spoil the fun.  
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
 
     
PHILOCTETES TO NEOPTOLEMUS    
Gods curse it!  
But it’s me the gods have cursed.   
They’ve let my name and story be wiped out.        
The real offenders got away with it  
And I am still here, rotting like a leper.  
Tell me, son. Achilles was your father.  
Did you ever maybe hear him mentioning  
A man who had inherited a bow—  
The actual bow and arrows that belonged  
To Hercules, and that Hercules gave him?  
Did you ever hear, son, about Philoctetes?  
About the snake-bite he got at a shrine  
When the first fleet was voyaging to Troy?  
And was marooned on the commanders' orders?  
Let me tell you, son, the way they deserted me.  
The sea and the sea-swell had me all worn out  
So I dozed and fell asleep under a rock  
Down the shore.  
And there and then, like that,
They headed off  
And they were delighted.    